name: "🚀 release"

on:
    release:
        types: [published]

permissions:
    id-token: write
    contents: read

jobs:
    release:
        name: "🚀 release"
        runs-on: ubuntu-latest
        steps:
            - name: "📚 checkout"
              uses: actions/checkout@v4
            - name: "🟢 node"
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: https://registry.npmjs.org/
            - name: "📦 publish"
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
